### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by neil-yc** [zyang1580/SML#1]
https://github.com/zyang1580/SML/blob/43f49d58776f512b1658353442e6309590b269a1/data/dataset.py#L95
Hi, Thanks for your contributions~ and i have some questions about dataset and algorithm in your papers.

1. dataset of yelp is in JSON format, and seems different from your data format. Can you provide your pre-process code or some sampe-examples?
2. In algorithm2, why the \hat(W_t) is updated twice with D_t ? which has been updated in algorithm1 with D_t.

Thanks.

**Comment by zyang1580** [comment]
Thank you for your attention to our work.
1. Pre-process code  is written by another co-author. I would tell him your need and he may reply to you later.  
sampe-examples: (array, and file is named as "period_id.npy") 
train: user_id, item_id;  test: user_id, pos_item_id, 999 neg_item_id   
(Our processed datasets will also be uploaded.)
2. Algorithm 1 is the offline training (simulate online).  Algorithm 2 is the online updating and testing. So the updates in the two algorithms are not related to each other.

**Comment by zyang1580** [comment]
Yelp has been uploaded. You can see the URL of Yelp in readme.
