### ISSUE TITLE
About Adressa Dataset

### ISSUE THREAD

**Issue by Luckfort** [zyang1580/SML#4]
Thanks for all your hard work!
May I have a chance to know that do we have Adressa (news) dataset? We haven't seen it in the netdisk.

**Comment by zyang1580** [comment]
> Thanks for all your hard work! May I have a chance to know that do we have Adressa (news) dataset? We haven't seen it in the netdisk.

Hi. There are both the original dataset and the one processed by ourselves. Which one do you need? If the former, you can directly download it via the link provided in the paper. If the latter one, please wait a few days. I will find it and send it to you.

**Comment by Luckfort** [comment]
That's great! May I have a chance to access the latter one? Thanks a lot!

**Comment by zyang1580** [comment]
link：https://rec.ustc.edu.cn/share/c9e9cac0-8c49-11ed-b493-416cf7d7e224

I have found two versions of processed datasets, and I am not sure enough which one was used. However, the shared one is the most possible.

**Comment by Luckfort** [comment]
Thanks very much for providing your dataset!
