### ISSUE TITLE
About Pre-train model in save_model

### ISSUE THREAD

**Issue by Luckfort** [zyang1580/SML#5]
May I ask about another issue? I wonder how you pre-trained the model, and I can't find any information about it in the paper.
What I've done is that I used the most effective full-retrain model (after tuning the hyperparameters) as the pretrained one (baseline_init), for training fine-tune method, the recall@20 will be much higher than that proposed in the paper, which was 0.86 or higher.
If I used gowalla dataset, it will reach to 0.95, which is very incredible.

**Comment by zyang1580** [comment]
It's been so long that I don't remember much. But you can find some instructions in the code, e.g.,
`# if you want to train a pre-train model, run model.base_train(29)`
[(line 666 in the baseline.py)](https://github.com/zyang1580/SML/blob/a30359a9bfe5b87b2efe7b28fde4f96258cebb86/model/baseline.py#L666)
and in base_train(), you could find more information about the pertaining, e.g., how to evaluate the trained model.

Your results are really surprising and incredible.  As far as I remember, some works take a similar setting to SML, and you could also refer to their corresponding results. For the Gowalla dataset, you could refer to Ding's paper[1]. Is there possible that the comparison is not fair or there is information leakage?

[1] Ding, Sihao, et al. "Causal incremental graph convolution for recommender system retraining." IEEE Transactions on Neural Networks and Learning Systems (2022).

**Comment by Luckfort** [comment]
Yeah, I saw it. Thanks a lot!

**Comment by Luckfort** [comment]
Your result is correct while I was wrong, because I used all the data to pre-train the model.
May I ask another question? How can I get the BCE_init.pkl? Is it the same method using model.base_train(29) in baseline.py? Are these two pre-train model (SML/baseline) actually the same one?
