### ISSUE TITLE
About the user and item amount of Yelp

### ISSUE THREAD

**Issue by Luckfort** [zyang1580/SML#6]
I found that in your paper, the user and item of Yelp is 59082, 122816, respectively. However, in your code, there are 122816 users and 59082 items, and in the .npy files, users are encoded in [0,122815], while items are encoded in [0,59081]. May I ask is the number in the paper reversed? Or the user and item has put reversely in your code?

**Comment by zyang1580** [comment]
The time has been too long, and I am not completely sure now. Perhaps you could try to extract the statistics based on the description of the dataset in the README file. The information in the actual dataset should be taken as the main reference.
